# Generated by Django 3.0.9 on 2020-08-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=255)),
                ('caller_email', models.EmailField(max_length=254)),
                ('caller_phone', models.IntegerField(default=0)),
                ('disposition', models.CharField(max_length=255)),
                ('callback_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
