# Generated by Django 3.0.9 on 2020-08-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='caller_phone',
            field=models.CharField(max_length=255),
        ),
    ]
