# Generated by Django 3.0.9 on 2020-08-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0007_auto_20200803_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='caller_details',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
